(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> "
p3
sS'layer'
p4
S'/home/juliana/web2py/applications/red_social/controllers/perfil.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n\n@auth.requires_login() \ndef index():\n    usuario_actual = db.perfil(user_id = db.auth_user.id)\n    mijo =usuario_actual('user_id')\n    #return dict()\n    return dict()\n\nresponse._vars=response._caller(index)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/juliana/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 10, in <module>\n  File "/home/juliana/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/juliana/web2py/gluon/tools.py", line 3774, in f\n    return action(*a, **b)\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 6, in index\n    mijo =usuario_actual(\'user_id\')\n  File "/home/juliana/web2py/gluon/packages/dal/pydal/objects.py", line 76, in __getitem__\n    raise KeyError\nKeyError\n'
p11
s.