(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'first_name'"
p3
sS'layer'
p4
S'/home/juliana/web2py/applications/red_social/controllers/perfil.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n@auth.requires_login() \ndef index():\n    nombre_completo = auth.user.first_name + " " + auth.user.last_name\n    ruta_imagen =  URL(\'downloads\',args = auth.user.foto)\n    return dict(nombre_completo = nombre_completo, \n                amigos = encuentra_mis_amigos(auth.user.id),\n                ruta_imagen = ruta_imagen)\n\n\n\ndef downloads():\n     return response.download(request, db)\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/juliana/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 16, in <module>\n  File "/home/juliana/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/juliana/web2py/gluon/tools.py", line 3774, in f\n    return action(*a, **b)\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 8, in index\n    amigos = encuentra_mis_amigos(auth.user.id),\n  File "/home/juliana/web2py/applications/red_social/models/logica.py", line 7, in encuentra_mis_amigos\n    otro_nombre = db.auth_user(amigo.amigo1.user).first_name\nAttributeError: \'NoneType\' object has no attribute \'first_name\'\n'
p11
s.