(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/home/juliana/web2py/applications/red_social/controllers/perfil.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n@auth.requires_login() \ndef index():\n    id_actual = auth.user.id\n    usuario_actual = db.perfil(db.perfil.user_id == id_actual)\n    form = DIV(\n        H1(auth.user.first_name + " " \n           + auth.user.last_name),\n            IMG(_src = URL(\'downloads\',args = usuario_actual.foto),\n              _width = 160, _height = 160),\n            )\n    lista_amigos = db(db.amistad.amigo2 == usuario_actual.id )\n    amigos = list()\n    for amigo in lista_amigos.select():\n        otro = db.perfil(amigo.amigo1)\n        otro_nombre = db.auth_user(otro.user_id).select().first()\n        amigos.append(otro_nombre)\n        \n    return dict(form = form, amigos = amigos)\n\n\n\ndef downloads():\n     return response.download(request, db)\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/juliana/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 27, in <module>\n  File "/home/juliana/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/juliana/web2py/gluon/tools.py", line 3774, in f\n    return action(*a, **b)\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 17, in index\n    otro_nombre = db.auth_user(otro.user_id).select().first()\n  File "/home/juliana/web2py/gluon/packages/dal/pydal/objects.py", line 90, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.